function CodeDefine() { 
this.def = new Array();
this.def["main"] = {file: "OpenLoopTestsAGV_main_c.html",line:34,type:"fcn"};
this.def["OpenLoopTestsAGV_DW"] = {file: "OpenLoopTestsAGV_c.html",line:26,type:"var"};
this.def["OpenLoopTestsAGV_M_"] = {file: "OpenLoopTestsAGV_c.html",line:29,type:"var"};
this.def["OpenLoopTestsAGV_M"] = {file: "OpenLoopTestsAGV_c.html",line:30,type:"var"};
this.def["OpenLoopTestsAGV_step0"] = {file: "OpenLoopTestsAGV_c.html",line:33,type:"fcn"};
this.def["OpenLoopTestsAGV_step1"] = {file: "OpenLoopTestsAGV_c.html",line:92,type:"fcn"};
this.def["OpenLoopTestsAGV_step2"] = {file: "OpenLoopTestsAGV_c.html",line:211,type:"fcn"};
this.def["OpenLoopTestsAGV_step3"] = {file: "OpenLoopTestsAGV_c.html",line:244,type:"fcn"};
this.def["OpenLoopTestsAGV_step4"] = {file: "OpenLoopTestsAGV_c.html",line:277,type:"fcn"};
this.def["OpenLoopTestsAGV_step5"] = {file: "OpenLoopTestsAGV_c.html",line:313,type:"fcn"};
this.def["OpenLoopTestsAGV_initialize"] = {file: "OpenLoopTestsAGV_c.html",line:349,type:"fcn"};
this.def["DW_OpenLoopTestsAGV_T"] = {file: "OpenLoopTestsAGV_h.html",line:79,type:"type"};
this.def["ConstP_OpenLoopTestsAGV_T"] = {file: "OpenLoopTestsAGV_h.html",line:92,type:"type"};
this.def["MCHP_UART1_TxStr"] = {file: "OpenLoopTestsAGV_types_h.html",line:34,type:"type"};
this.def["MCHP_UART1_RxStr"] = {file: "OpenLoopTestsAGV_types_h.html",line:45,type:"type"};
this.def["RT_MODEL_OpenLoopTestsAGV_T"] = {file: "OpenLoopTestsAGV_types_h.html",line:57,type:"type"};
this.def["OpenLoopTestsAGV_ConstP"] = {file: "OpenLoopTestsAGV_data_c.html",line:26,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:84,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:89,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:94,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:101,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:108,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:115,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:122,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:129,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:136,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:154,type:"type"};
this.def["ADC1BuffChannelA"] = {file: "MCHP_ADC1_Interrupt_c.html",line:5,type:"var"};
this.def["__attribute__"] = {file: "MCHP_ADC1_Interrupt_c.html",line:6,type:"fcn"};
this.def["MCHP_UART1_Rx"] = {file: "MCHP_UART1_Rx_Interrupt_c.html",line:4,type:"var"};
this.def["__attribute__"] = {file: "MCHP_UART1_Rx_Interrupt_c.html",line:6,type:"fcn"};
this.def["MCHP_UART1_Tx"] = {file: "MCHP_UART1_Tx.Interrupt_c.html",line:5,type:"var"};
this.def["__attribute__"] = {file: "MCHP_UART1_Tx.Interrupt_c.html",line:7,type:"fcn"};
this.def["CAN1_TX_CONTROLS"] = {file: "can1_c.html",line:77,type:"type"};
this.def["CAN1_Initialize"] = {file: "can1_c.html",line:96,type:"fcn"};
this.def["CAN1_TransmitEnable"] = {file: "can1_c.html",line:200,type:"fcn"};
this.def["CAN1_ReceiveEnable"] = {file: "can1_c.html",line:228,type:"fcn"};
this.def["CAN1_transmit"] = {file: "can1_c.html",line:260,type:"fcn"};
this.def["CAN1_receive"] = {file: "can1_c.html",line:304,type:"fcn"};
this.def["CAN1_isBusOff"] = {file: "can1_c.html",line:357,type:"fcn"};
this.def["CAN1_isRXErrorPassive"] = {file: "can1_c.html",line:370,type:"fcn"};
this.def["CAN1_isTXErrorPassive"] = {file: "can1_c.html",line:383,type:"fcn"};
this.def["CAN1_messagesInBuffer"] = {file: "can1_c.html",line:395,type:"fcn"};
this.def["CAN1_sleep"] = {file: "can1_c.html",line:442,type:"fcn"};
this.def["can1.c:CAN1_DMACopy"] = {file: "can1_c.html",line:471,type:"fcn"};
this.def["can1.c:CAN1_MessageToBuffer"] = {file: "can1_c.html",line:533,type:"fcn"};
this.def["DMA_Initialize"] = {file: "dma_c.html",line:51,type:"fcn"};
this.def["__attribute__"] = {file: "dma_c.html",line:137,type:"fcn"};
this.def["__attribute__"] = {file: "dma_c.html",line:142,type:"fcn"};
this.def["__attribute__"] = {file: "dma_c.html",line:148,type:"fcn"};
this.def["DMA_Channel1_Tasks"] = {file: "dma_c.html",line:153,type:"fcn"};
this.def["__attribute__"] = {file: "dma_c.html",line:163,type:"fcn"};
this.def["DMA_Channel2_Tasks"] = {file: "dma_c.html",line:168,type:"fcn"};
this.def["__attribute__"] = {file: "dma_c.html",line:178,type:"fcn"};
this.def["DMA_Channel3_Tasks"] = {file: "dma_c.html",line:183,type:"fcn"};
this.def["__attribute__"] = {file: "ecan1_c.html",line:56,type:"fcn"};
this.def["__attribute__"] = {file: "ecan1_c.html",line:57,type:"fcn"};
this.def["__attribute__"] = {file: "ecan1_c.html",line:58,type:"fcn"};
this.def["__attribute__"] = {file: "ecan1_c.html",line:59,type:"fcn"};
this.def["__attribute__"] = {file: "ecan1_c.html",line:60,type:"fcn"};
this.def["ECAN1_Initialize"] = {file: "ecan1_c.html",line:66,type:"fcn"};
this.def["ECAN1_TransmitEnable"] = {file: "ecan1_c.html",line:81,type:"fcn"};
this.def["ECAN1_ReceiveEnable"] = {file: "ecan1_c.html",line:96,type:"fcn"};
this.def["ECAN1_transmit"] = {file: "ecan1_c.html",line:115,type:"fcn"};
this.def["ECAN1_receive"] = {file: "ecan1_c.html",line:131,type:"fcn"};
this.def["ECAN1_isBusOff"] = {file: "ecan1_c.html",line:146,type:"fcn"};
this.def["ECAN1_isRXErrorPassive"] = {file: "ecan1_c.html",line:160,type:"fcn"};
this.def["ECAN1_isTXErrorPassive"] = {file: "ecan1_c.html",line:174,type:"fcn"};
this.def["ECAN1_messagesInBuffer"] = {file: "ecan1_c.html",line:187,type:"fcn"};
this.def["ECAN1_sleep"] = {file: "ecan1_c.html",line:199,type:"fcn"};
this.def["ECAN1_Simulink_Init"] = {file: "fonctionsAGV_c.html",line:10,type:"fcn"};
this.def["ECAN1_Simulink_Transmit"] = {file: "fonctionsAGV_c.html",line:44,type:"fcn"};
this.def["ECAN1_Simulink_Receive"] = {file: "fonctionsAGV_c.html",line:68,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["OpenLoopTestsAGV_main_c.html"] = "../OpenLoopTestsAGV_main.c";
	this.html2Root["OpenLoopTestsAGV_main_c.html"] = "OpenLoopTestsAGV_main_c.html";
	this.html2SrcPath["OpenLoopTestsAGV_c.html"] = "../OpenLoopTestsAGV.c";
	this.html2Root["OpenLoopTestsAGV_c.html"] = "OpenLoopTestsAGV_c.html";
	this.html2SrcPath["OpenLoopTestsAGV_h.html"] = "../OpenLoopTestsAGV.h";
	this.html2Root["OpenLoopTestsAGV_h.html"] = "OpenLoopTestsAGV_h.html";
	this.html2SrcPath["OpenLoopTestsAGV_private_h.html"] = "../OpenLoopTestsAGV_private.h";
	this.html2Root["OpenLoopTestsAGV_private_h.html"] = "OpenLoopTestsAGV_private_h.html";
	this.html2SrcPath["OpenLoopTestsAGV_types_h.html"] = "../OpenLoopTestsAGV_types.h";
	this.html2Root["OpenLoopTestsAGV_types_h.html"] = "OpenLoopTestsAGV_types_h.html";
	this.html2SrcPath["OpenLoopTestsAGV_data_c.html"] = "../OpenLoopTestsAGV_data.c";
	this.html2Root["OpenLoopTestsAGV_data_c.html"] = "OpenLoopTestsAGV_data_c.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MCHP_ADC1_Interrupt_c.html"] = "../MCHP_ADC1_Interrupt.c";
	this.html2Root["MCHP_ADC1_Interrupt_c.html"] = "MCHP_ADC1_Interrupt_c.html";
	this.html2SrcPath["MCHP_UART1_Rx_Interrupt_c.html"] = "../MCHP_UART1_Rx_Interrupt.c";
	this.html2Root["MCHP_UART1_Rx_Interrupt_c.html"] = "MCHP_UART1_Rx_Interrupt_c.html";
	this.html2SrcPath["MCHP_UART1_Tx.Interrupt_c.html"] = "../MCHP_UART1_Tx.Interrupt.c";
	this.html2Root["MCHP_UART1_Tx.Interrupt_c.html"] = "MCHP_UART1_Tx.Interrupt_c.html";
	this.html2SrcPath["MCHP_modelInclude_h.html"] = "../MCHP_modelInclude.h";
	this.html2Root["MCHP_modelInclude_h.html"] = "MCHP_modelInclude_h.html";
	this.html2SrcPath["can1_c.html"] = "../../../../../Matlab/MicrochipDCMotorControl/MicrochipDCMotorControl/ECAN/ECAN1/can1.c";
	this.html2Root["can1_c.html"] = "can1_c.html";
	this.html2SrcPath["dma_c.html"] = "../../../../../Matlab/MicrochipDCMotorControl/MicrochipDCMotorControl/ECAN/ECAN1/dma.c";
	this.html2Root["dma_c.html"] = "dma_c.html";
	this.html2SrcPath["ecan1_c.html"] = "../../../../../Matlab/MicrochipDCMotorControl/MicrochipDCMotorControl/ECAN/ECAN1/ecan1.c";
	this.html2Root["ecan1_c.html"] = "ecan1_c.html";
	this.html2SrcPath["fonctionsAGV_c.html"] = "../../../../../Matlab/MicrochipDCMotorControl/MicrochipDCMotorControl/ECAN/ECAN1/fonctionsAGV.c";
	this.html2Root["fonctionsAGV_c.html"] = "fonctionsAGV_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"OpenLoopTestsAGV_main_c.html","OpenLoopTestsAGV_c.html","OpenLoopTestsAGV_h.html","OpenLoopTestsAGV_private_h.html","OpenLoopTestsAGV_types_h.html","OpenLoopTestsAGV_data_c.html","rtwtypes_h.html","rtmodel_h.html","MCHP_ADC1_Interrupt_c.html","MCHP_UART1_Rx_Interrupt_c.html","MCHP_UART1_Tx.Interrupt_c.html","MCHP_modelInclude_h.html","can1_c.html","dma_c.html","ecan1_c.html","fonctionsAGV_c.html"];
